In [2]:
import torch

# create a scalar 
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
# vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.shape

torch.Size([2])

In [7]:
vector.dtype

torch.int64

In [8]:
vector.ndim

1

In [9]:
# Matrix
matrix = torch.tensor([[7,8],
                       [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
print(matrix.ndim)
print(matrix.shape)
print(matrix.dtype)

2
torch.Size([2, 2])
torch.int64


In [13]:
#Tensor
tensor = torch.tensor([[[1,2,3],
                       [4,5,6],
                       [5,6,4]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [5, 6, 4]]])

In [14]:
tensor.shape

torch.Size([1, 3, 3])

In [15]:
tensor.ndim

3

In [18]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [5, 6, 4]])

In [25]:
# random tensors
random_tensor = torch.rand(2, 3, 4)
random_tensor

tensor([[[0.0086, 0.3686, 0.6087, 0.1378],
         [0.3417, 0.1447, 0.5667, 0.2440],
         [0.6279, 0.5583, 0.2700, 0.8381]],

        [[0.6337, 0.3385, 0.8570, 0.5101],
         [0.9548, 0.9132, 0.3001, 0.2009],
         [0.9772, 0.6597, 0.6649, 0.9019]]])

In [26]:
random_tensor.ndim

3